version: "1"

services:
  database:
    image: mysql
    container_name: test_db
    environment:
      - MYSQL_DATABASE=tester
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - 3307:3306

  application:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database
    container_name: app1

networks:
  spring-boot-mysql-network:
    driver: bridge