INSERT INTO test.company_entity (company_code, company_name) VALUES ('iPhone 9', 'iPhone 9');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('iPhone X', 'iPhone X');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Samsung Universe 9', 'Samsung Universe 9');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('OPPOF19', 'OPPOF19');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Huawei P30', 'Huawei P30');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('MacBook Pro', 'MacBook Pro');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Samsung Galaxy Book', 'Samsung Galaxy Book');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Microsoft Surface Laptop 4', 'Microsoft Surface Laptop 4');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Infinix INBOOK', 'Infinix INBOOK');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('HP Pavilion 15-DK1056WM', 'HP Pavilion 15-DK1056WM');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('perfume Oil', 'perfume Oil');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Brown Perfume', 'Brown Perfume');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Fog Scent Xpressio Perfume', 'Fog Scent Xpressio Perfume');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Non-Alcoholic Concentrated Perfume Oil', 'Non-Alcoholic Concentrated Perfume Oil');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Eau De Perfume Spray', 'Eau De Perfume Spray');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Hyaluronic Acid Serum', 'Hyaluronic Acid Serum');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Tree Oil 30ml', 'Tree Oil 30ml');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Oil Free Moisturizer 100ml', 'Oil Free Moisturizer 100ml');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Skin Beauty Serum.', 'Skin Beauty Serum.');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Freckle Treatment Cream- 15gm', 'Freckle Treatment Cream- 15gm');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('- Daal Masoor 500 grams', '- Daal Masoor 500 grams');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Elbow Macaroni - 400 gm', 'Elbow Macaroni - 400 gm');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Orange Essence Food Flavou', 'Orange Essence Food Flavou');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('cereals muesli fruit nuts', 'cereals muesli fruit nuts');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Gulab Powder 50 Gram', 'Gulab Powder 50 Gram');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Plant Hanger For Home', 'Plant Hanger For Home');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Flying Wooden Bird', 'Flying Wooden Bird');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('3D Embellishment Art Lamp', '3D Embellishment Art Lamp');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Handcraft Chinese style', 'Handcraft Chinese style');
INSERT INTO test.company_entity (company_code, company_name) VALUES ('Key Holder', 'Key Holder');